apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: javaapp-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javaapp
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
